server:
  port: 8082
spring:
  application:
    name: ratings-data-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8085/eureka/